services:
  helpdesk:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - helpdesk-db:/data
    environment:
      - DATABASE_URL=sqlite:////data/app.db
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - helpdesk

volumes:
  helpdesk-db: